### ISSUE TITLE
referencing by column name not working..?

### ISSUE THREAD

**Issue by gregsadetsky** [mechatroner/sublime_rainbow_csv#37]
Hi,

I don't seem to be able to use the `a.col_name` notation when making queries. The typical `a1` (i.e. `a` + int) notation works.

I created this test file:

```csv
col1,col2,col3,vehicle_price,Vehicle type
test1,test2,test3,20,car
test1,test2,test3,200,plane
test1,test2,test3,2000,boat
```

and tried running `select a.col1` but got this error:

```
Details:
query execution
At record 1, Details: 'RBQLRecord' object has no attribute 'col1'
```

I also tried running the `select len(a.vehicle_price) / 10, a2 where int(a.vehicle_price) < 500 and a['Vehicle type'] in ["car", "plane", "boat"] limit 20` query from the README ([here](https://github.com/mechatroner/sublime_rainbow_csv/blob/master/README.md?plain=1#L254)) and got a similar error (`... RBQLRecord has no attribute ...`)

I'm running the latest 2.8.0 release of the package.

Thank you!

**Comment by gregsadetsky** [comment]
I used `git bisect` and found the commit that introduced the problem: [it's this one](https://github.com/mechatroner/sublime_rainbow_csv/commit/2da337da01cf472d85ccbfa91387915cda8d5a43).

The `select a1.col_name` syntax works in the commit right before that.

Thanks!

**Comment by mechatroner** [comment]
Hi Greg,
Sorry about this, At first I thought that this is a bug, but it is actually a feature and I should have added a meaningful error message before introducing this breaking change.
But it should work if you add `with (header)` at the end of the query, the syntax is similar to `with (nolock)` modifier in MS SQL server - and this would automatically skip the first record e.g. you can now use `select int(a.col_name)` syntax without adding `where NR > 1`. Also, this always carries the header record to the output e.g. `Select top 10 * order by a1 with (header)`. And you can also set `rbql_with_headers` setting to true if the majority of the tables you are dealing with have headers, and if one or two don't have them - you can override it with `with (noheader)`. It would be cool if Sublime Text would allow extensions to create a checkbox to control this with GUI on a per-query basis, but there is no such option right now, unfortunately, so the only 2 ways to control this are either the setting or the query modifier.
Please let me know if it didn't work! Thanks!

**Comment by gregsadetsky** [comment]
Ah, that makes perfect sense, thank you! `with (header)` worked, and the `rbql_with_headers` setting is really useful. I just enabled it and yes, `select a.col_name` works! That's really great.

Just out of curiosity, is there any downside to having `rbql_with_headers` always on?

(I'll also close the issue since there isn't a bug in the package)

**Comment by mechatroner** [comment]
Glad it worked!

>  Just out of curiosity, is there any downside to having rbql_with_headers always on?

I think the only downside is that it is possible to forget that `rbql_with_headers` is on, run a query using `a1`, `a2` etc, and inadvertently skip the first row.
